# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    goarch:
      - amd64
      - arm
      - arm64
      - 386
brews:
   -
    name: gogen
    tap:
      owner: ksrichard
      name: homebrew-tap
    download_strategy: CurlDownloadStrategy.
    folder: Formula
    caveats: "./gogen generate --help
              Generating projects/folder structures based on a template

              Usage:
                gogen generate [flags]

              Flags:
                -h, --help                  help for generate
                -o, --output-dir string     Output folder where result files will be generated
                -t, --template-dir string   Template folder to be used for generation
                -v, --vars stringToString   Variables for generation (default [])"
    homepage: "https://github.com/ksrichard/gogen"
    description: "Simple yet powerful dynamic project generation"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
